# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30, verbose_name='书名')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAN', to='TestApp.Author')),
            ],
        ),
    ]
