# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pubtime',
            field=models.DateField(default=datetime.datetime(2018, 7, 24, 11, 48, 10, 233851), verbose_name='出版时间'),
        ),
    ]
